#!/bin/sh

#Valid flags
flags=(
    '-t|--target_arch'
    '-c|--components'
    '-h|--help')

#Realpath to Current Working Directory
CWD=$(dirname $(realpath $0));

#Paths
ELECTRON_PATH="$CWD/electron";
BRIGHTRAY_PATH="$ELECTRON_PATH/vendor/brightray";
LIBCHROMIUM_PATH="$BRIGHTRAY_PATH/vendor/libchromiumcontent";

#Pkg-Config
sysPkgs="gtk+-3.0 wayland-protocols gl egl glib-2.0 x11 gdk-3.0
        gmodule-2.0 gthread-2.0 gtk+-unix-print-3.0
        libpulse atk"

#Libchromiumcontent
libchromiumcontent_bootstrap() {
    #TODO update install-sysroot.py to use jessie
    cd $CWD
    patch -N $LIBCHROMIUM_PATH/script/update \
        < patches/libchromiumcontent-update.patch

    #Sync libchromiumcontent submodules
    cd $LIBCHROMIUM_PATH;
    python script/bootstrap;

    #Use_gtk3 to defines via sed
    sed -e "s|'use_gtk3': 1, ||" \
        -e "s|'use_dbus': 1,|'use_dbus': 1, 'use_gtk3': 1, |" \
        -i chromiumcontent/chromiumcontent.gypi

    #Download src
    python script/update -t $arch;

    #No use_sysroot in common.gypi via sed
    sed -e "s|'use_sysroot%': 1,|'use_sysroot%': 0,|" \
        -i vendor/chromium/src/build/common.gypi

    #Update gyp
    python script/update -t $arch -s;
}
libchromiumcontent_build() {
    #TODO: integrate pkg-config in a more friendly way
    pkg-config --cflags $sysPkgs --libs $sysPkgs
    export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/share/pkgconfig;

    #Build type
    if [[ $components == 'static' ]]; then
        component_flag="--no_shared_library"
    fi

    #Build
    cd $LIBCHROMIUM_PATH;
    python script/build $component_flag -t $arch;
}
libchromiumcontent_dist() {
    #Build type
    if [[ $components == 'static' ]]; then
        component_flag="-c static_library"
    fi

    cd $LIBCHROMIUM_PATH;
    python script/create-dist $component_flag -t $arch --no_zip;
}

#Electron
electron_bootstrap() {
    cd $CWD

    #Brightray fails if files aren't in brightray/vendor/download
    DL_PATH=$BRIGHTRAY_PATH/vendor/download;
    LIBCC_PATH=$DL_PATH/libchromiumcontent;

    mkdir -p $DL_PATH;
    mkdir -p $LIBCC_PATH;

    ln -sf $LIBCHROMIUM_PATH/dist/main/ffmpeg $LIBCC_PATH/ffmpeg
    ln -sf $LIBCHROMIUM_PATH/dist/main/src $LIBCC_PATH/src
    ln -sf $LIBCHROMIUM_PATH/dist/main/static_library $LIBCC_PATH/static_library

    if [[ $components == 'all' ]]; then
        ln -sf $LIBCHROMIUM_PATH/dist/main/shared_library $LIBCC_PATH/shared_library
    else
        mkdir -p $LIBCC_PATH/shared_library
    fi

    #TODO update install-sysroot.py to use jessie
    patch -N $ELECTRON_PATH/script/bootstrap.py \
        < patches/electron-bootstrap.patch

    cd $ELECTRON_PATH;

    #Update toolchain
    sed -e "s|'sysroot%': '<(sysroot)'|'sysroot%': ''|" \
        -e "s|'<!(<(source_root)/tools/linux/sysroot_ld_path.sh <(sysroot))',||" \
        -e 's|<(source_root)/tools/linux/pkg-config-wrapper "<(sysroot)" "<(target_arch)" "<(system_libdir)"|pkg-config|' \
        -i toolchain.gypi

    #Update brightray
    sed -e "s|'linux_system_libraries': 'gtk+-2.0|'linux_system_libraries': 'gtk+-3.0|" \
        -e "s|'-latomic',||" \
        -e "s|'-lpthread',|'-lpthread','-latomic',|" \
        -i vendor/brightray/brightray.gyp

    #Local libchromiumcontent flags
    #Pull Request Opportunity, script/bootstrap.py wrongly requires
    #libcc_shared_library_path when building only the release version
    libcc_flag="--libcc_source_path="$LIBCC_PATH"/src
                --libcc_static_library_path="$LIBCC_PATH"/static_library
                --libcc_shared_library_path="$LIBCC_PATH"/shared_library";

    python script/bootstrap.py -v $libcc_flag --target_arch=$arch
}
electron_build() {
    cd $ELECTRON_PATH;

    if [[ $components == "static" ]]; then
        build_flag="-c R"
    fi

    python script/build.py $build_flag;
}
electron_dist() {
    cd $ELECTRON_PATH;
    python script/create-dist.py

    #symlink dist folder to root dir
    ln -sf $ELECTRON_PATH/dist $CWD/dist
}

#Clean
clean() {
    cd $CWD;
    rm -rf $ELECTRON_PATH dist;
}

#Update submodules to remote's master
update() {
    cd $CWD;
    mkdir -p $ELECTRON_PATH;
    git submodule update --checkout --recursive
}

#Main
main() {
    #Available FNs
    funcs=$(typeset -f | awk '/ \(\) $/ && !/^(main) / {print $1}');

    #Load ./utils/*.sh helpers
    for f in $(find ${CWD}/utils -name '*.sh'); do
        . $f
    done

    #Parse Command Line Args
    if [[ $@ ]]; then
        eval $(argsToArray $@);
    fi

    #Get system architecture
    arch=$(archParser $(getArg --target_arch))

    #Help Menu || Show if arch is un-detectable
    if [[ $@ =~ -h|--help || ! $arch ]]; then
        if [[ ! $arch ]]; then
            echo "Unable to detect architecture type.";
            echo "----";
        fi

        helpMenu $funcs;
        return;
    fi

    #Make sure we use Python 2 - ugh
    if [[ ! $(python --version) =~ "2."  ]]; then
        PYENV_PATH="$CWD/.tmp"
        mkdir -p $PYENV_PATH

        # TODO: figure out a bulletproof way to find python 2
        ln -sf /usr/bin/python2 "$PYENV_PATH/python"

        OG_PATH=($(echo $PATH|sed "s|${PYENV_PATH}:||g"))
        export PATH=$PYENV_PATH:$OG_PATH
    fi

    #Build components | Defaults to Release
    components=$(getArg --components)
    if [[ ! $components || $components != 'all' ]]; then
        components='static'
    fi

    #Is Command Function
    if [[ $1 && $funcs =~ $1 ]]; then
        $1
    #No Command, execute all
    else
        #update submodules
        update

        #Bootstrap, patch and build Libchromiumcontent
        libchromiumcontent_bootstrap;
        libchromiumcontent_build;
        libchromiumcontent_dist;

        #Bootstrap, patch and build Electron
        electron_bootstrap;
        electron_build;
        electron_dist;
    fi

    #Reset Python Path
    if [[ $PYENV_PATH ]]; then
        export PATH=$OG_PATH
    fi
}

main $@
